version: '3.7'
services:

    db:
        container_name: wp-hyperdrive-nl-db
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wp-hyperdrive-nl
            MYSQL_USER: highfive
            MYSQL_PASSWORD: highfive
        volumes:
            - database:/var/lib/mysql
        ports:
            - 3309:3306

    web:
        container_name: wp-hyperdrive-nl-web
        build: ./.docker
        links:
            - db:db
        depends_on:
            - db
        volumes:
            - ./:/var/www
            - ./public:/var/www/html
        user: ${CURRENT_UID}
        environment:
            - VIRTUAL_PORT=80
            - VIRTUAL_HOST=wp-hyperdrive-nl.test
volumes:
    database:
networks:
    default:
        external:
            name: nginx-proxy
